# Generated by Django 5.0.6 on 2024-09-16 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='order_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_no', models.CharField(max_length=50)),
                ('user_id', models.CharField(max_length=50)),
                ('product', models.CharField(max_length=50)),
                ('total_prise', models.CharField(max_length=50)),
                ('payment', models.CharField(max_length=50)),
                ('shypping_address', models.CharField(max_length=50)),
                ('order_status', models.CharField(max_length=50)),
            ],
        ),
    ]
