# Generated by Django 5.1 on 2024-10-28 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_app', '0002_remove_custom_user_username'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='custom_user',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='custom_user',
            name='address',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='custom_user',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='custom_user',
            name='mobile',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
