# Generated by Django 5.0.6 on 2024-09-16 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='product_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.CharField(max_length=50)),
                ('quantity', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=250)),
                ('descount_price', models.CharField(max_length=250)),
                ('descount_percent', models.CharField(max_length=250)),
                ('on_scale', models.CharField(max_length=250)),
                ('images', models.CharField(max_length=250)),
            ],
        ),
    ]
